### ISSUE TITLE
File too short on linux

### ISSUE THREAD

**Issue by leandrodreamer** [kroketio/godot-webview-meta#1]
Hi, i was giving a try to the demo on linux (godot 4.4 dev4) but it gives this error

```
Can't open dynamic library: /home/user/4.4test/addons/webview/libgdwebview.linux.x86_64.so. Error: /home/user/4.4test/addons/webview/linux_x86_64-runtime/lib/libQt6QuickWidgets.so.6: file too short.
  Can't open GDExtension dynamic library: 'res://addons/webview/webview.gdextension'.
```
the files seem to contain the name of another lib file, not sure if that's intended
![image](https://github.com/user-attachments/assets/d7497f6f-6fc5-41cc-8b1f-6c1899098107)

**Comment by leandrodreamer** [comment]
Talking with the dev on discord found out that some zip extractors may not keep symlinks, extracting the addon with unzip instead of ark fixes this issue

**Comment by WinnerWind** [comment]
Adding to this, use the Legacy Zip Extracter in ARK (Settings -> Plugins) instead of the default zipping plugin to fix this.

Just disable the second zip-unzipper.
